### ISSUE TITLE
Slowdown once arena started.

### ISSUE THREAD

**Issue by Tigergruppe** [rplcnn/SuperSkyWars#3]
Hello!

I just installed this plugin last night and everything was working splendidly until I actually had people in a game. We setup an arena for 8 players with a minimum of 8 players as well. We had no lobby defined. Once we started the game we noticed some player spawn points (glass boxes) were doubling up. People were killing eachother in the boxes before even starting. Seconds later the entirety of the server ground to a halt. There were no errors in console, but TPS tanked to 2.0 when it was a solid 20 beforehand. 

Please help! I would love to use this!

Also! Is Umbaska able to replace WildSkript as the project is abandoned and the team started Umbaska as their new project?

http://dev.bukkit.org/bukkit-plugins/umbaska/

**Comment by rplcnn** [comment]
Fixed, disable all scoreboards.
