### ISSUE TITLE
Error when reloading scripts - SS-Main and SS-Files

### ISSUE THREAD

**Issue by GS-PandaGaming** [rplcnn/SuperSkyWars#6]
ugh. I buy a plugin that doesn't work... It would be great to be helped! Sp I updated and downloaded the most recent versions of - Skquerey, WildSkript, Skript, and SuperSkywars.

Here is some error logs...

http://pastebin.com/whhWmqSE

**Comment by rplcnn** [comment]
i think problem is your wildskript
